
  // This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy
  export const  environment = {
    production: false,
    title:"Development",
    CORSURL:'',
    SEARCHURL:'',
    BASEURL:'',
  }
