
  // This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy
  export const  environment = {
    production: false,
    title:"Development",
    CORSURL:'https://bash-cors-any.herokuapp.com/',
    SEARCHURL:'https://www.berlin.de/sen/finanzen/service/zuwendungsdatenbank/index.php/index/index.json',
    BASEURL:'https://daten.berlin.de/datensaetze/rss.xml/berliner-stra%C3%9Fen-und-volksfeste-2020'
  }
